services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PORT: 3000
      DATABASE_URL: mysql://root:shinthant101207@db:3306/ChatApp
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shinthant101207
      MYSQL_DATABASE: ChatApp
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pshinthant101207"]
      interval: 5s
      timeout: 5s
      retries: 20